### ISSUE TITLE
Espanso file

### ISSUE THREAD

**Issue by smeech** [willwade/Abbreviation-Finder#1]
Espanso currently only recognises files with a `.yml` extension (not `.yaml`) so it would be worth changing that for your download option.

Additionally, people use different trigger prefixes so it would be nice if they could set their own - although the colon is widely used it is not required (unlike AutoHotKey, IIRC). At least changing it in a text editor is simple.

I'm responsible for all the recent Espanso documentation updates, so happy to discuss further.

Thanks for bringing your tool to our attention, and configuring it for Espanso!

**Comment by willwade** [comment]
Thanks @smeech  - one thing - I noticed the comment about removing quotes. Mind giving me an example?

The yaml->yml fixed and removing the forced prepend now done - but need to think how any letter could be used..

**Comment by smeech** [comment]
I *don't* think you should change the quotes - if you're interested, read my brief  latest addition to the Espanso [docs](https://espanso.org/docs/matches/quotes/) which just happens to be relevant. 

The colon is the most widely used Espanso prefix but lots use semi-colons, and for abbreviations one could manage without, but then we get into [`word: true`](https://espanso.org/docs/matches/basics/#word-triggers) territory, which is another story. 

The rest I'll check when I'm home.

**Comment by smeech** [comment]
Thank you - sorry if I confused you!
